# Generated by Django 6.0.1 on 2026-01-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('welcome_title', models.CharField(max_length=255)),
                ('welcome_subtitle', models.CharField(max_length=255)),
                ('welcome_text', models.TextField()),
                ('welcome_image', models.ImageField(upload_to='home_images/')),
            ],
        ),
    ]
